//crear usuario
POST http://localhost:5000/users
Content-Type: application/json
{
    "id": "20700200",
    "name": "Estudiante",
    "email": "estudiante@ucm.cl",
    "password": "estudiantepassword",
    "confPassword": "estudiantepassword",
    "role": "5",
    "telefono": "1015"
}
### 
// obtener todos los usuarios
GET http://localhost:5000/users

###
// obtener un solo usuario
GET http://localhost:5000/users/7da6e099-14b9-451b-9ab1-c7a30c1332b9


### 
// actualizar usuario
PATCH http://localhost:5000/users/7da6e099-14b9-451b-9ab1-c7a30c1332b9
Content-Type: application/json

{
    "name": "Jefe de Carrera",
    "rut" : "16700200",
    "email": "jefecarrera@gmail.com",
    "password": "jefecarrera",
    "confPassword": "jefecarrera",
    "role": "2"
}


###
// eliminar usuario

DELETE http://localhost:5000/users/1d4d1a8e-a5e0-4251-a45c-dbe36c268734
 

###
// iniciar sesion

POST http://localhost:5000/login
Content-Type: application/json

{
    "id": "20705543",
    "password": "adminuser"
}

### ver sesion
GET http://localhost:5000/me

### cerrar sesion
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/preguntas_frecuentes

###
GET http://localhost:5000/pregunta